### ISSUE TITLE
Slide 29 (App Store + Per tenant extensions – Number range and names ): too rough description

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/BCUpgrade#17]
The description on slide 29 is too compact.

Seems to me  very relevant slide with actually a lot of info, but needs more elaboration as it throws (surely to me) a number of questions.

It states:

> If you complete renaming and renumbering in C/AL, we will move full tables automatically to extensions if the ID and the Name Matches

**Question 1**: looking at the example the names of TAB50000 and TAB55000000 do not exactly match. DIfference is "NKC - ", including 3 letter prefix. Does the platform disregard this prefix part (including "- ") and sees that the main part of the table names match?

**Question 2**: is the ID matching refering to the field IDs?

> follow app source process to get a 3-letter prefix and a range

**Question 3**: Prefix only? How about suffix?

Or I am I totally on the wrong track and is the matching something different?

**Comment by nikolakukrika** [comment]
Question 1 - on previous slides it is explained that this move should be done in C/AL. Platform will not do it. C/AL will rename on force sync, that is the recommendation. Renumbering is tricky.

Question 2 -  Fields should be only if you have table extensions. Otherwise it is table IDs. I assume this should be known to the partners.

Question 3 - Updated. 

Please let me know if I should update anything else (reactivate the issue)
