### ISSUE TITLE
How move C/AL table fields to separate extensions

### ISSUE THREAD

**Issue by daansaveyn** [microsoft/BCUpgrade#28]
We're currently facing the following situation:

In C/AL we added some custom fields to the UOM table. During the move to AL we've divided our solution in several apps. The original C/AL custom fields were moved to 2 table extensions. In order to facilitate the upgrade from C/AL to AL we import a fob file containing the Cronus UOM table and move the data of the custom fields to an upgrade table. 

How can we move the data to the correct table extension during the data upgrade of each app? This especially when you have multiple dependant apps?

**Comment by nikolakukrika** [comment]
Hello,

Sorry for the late reply, I was on vacation. 
In the slide deck, slides 45 and 46 cover this topic.

If you are still on C/AL then you can use extension uplift. It is described on slide 45 - you would copy the values to the buffer tables. You can make the buffer tables part of the new extension, it is the cleanest in this way since you can uninstall it.

Also from C/Al you can see the solution our MVP did on slide 46. 

We are working on a feature to support AL to AL moving of the fields.

Let me know if you have any additional questions
