### ISSUE TITLE
Need more information on a Warning: Business Central v17

### ISSUE THREAD

**Issue by AnantshreeChandola** [microsoft/BCUpgrade#30]
Hello everyone,
 I need help in fixing the following warning while upgrading an app from v16 to v17:

Method 'CreateWebService' is marked for removal. Reason: Method scope will be moved down to On-Prem. This function does not work in SaaS.. Tag: 16.0.

The compiler doesn't give any other information about this or the alternative to use for the above function.

**Comment by nikolakukrika** [comment]
Hello,

These kind of questions are better on yammer, I would recommend joining here:
https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=5059035

If you have issues, let me know and we can unblock the join.
For your question refactor the calls to CreateTenantWebService. OnPrem it will work the same. In SaaS it creates an entry for the specific tenant, since the CreateWebService would create a web service for all tenants and should not be  used.
